/**
 * generated by Xtext 2.13.0
 */
package ac.soton.xeventb.xmachine.tests;

import ac.soton.xeventb.xmachine.tests.XMachineInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(XMachineInjectorProvider.class)
@SuppressWarnings("all")
public class XMachineParsingTest {
  @Inject
  private /* ParseHelper<Machine> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field XMachineParsingTest.parseHelper refers to the missing type Machine"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
